version: 2
registries:
  npm-registry-registry-npmjs-org:
    type: npm-registry
    url: https://registry.npmjs.org
    token: "${{secrets.NPM_REGISTRY_REGISTRY_NPMJS_ORG_TOKEN}}"

updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.35
  - dependency-name: "@types/jest"
    versions:
    - 26.0.21
  - dependency-name: ts-jest
    versions:
    - 26.5.2
  - dependency-name: husky
    versions:
    - 5.1.0
    - 5.1.2
  - dependency-name: "@types/koa"
    versions:
    - 2.13.0
  registries:
  - npm-registry-registry-npmjs-org
